[package]
org = "danesh"
name = "demo_sqlite_db"
version = "0.1.0"
distribution = "2201.11.0"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId = "org.xerial"
artifactId = "sqlite-jdbc"
version = "3.49.1.0"
